CREATE DATABASE DUAN1a
USE DUAN1a
GO
IF OBJECT_ID('Users') IS NOT NULL
DROP TABLE Users
CREATE TABLE Users(
IdUser INT IDENTITY(1,1) PRIMARY KEY,
HoTen NVARCHAR(225),
NgaySinh DATE,
GioiTinh BIT,
DiaChi NVARCHAR(225),
Sdt VARCHAR(10),
Email VARCHAR(225),
Luong MONEY,
Role BIT,
TrangThai BIT
)

IF OBJECT_ID('TaiKhoan') IS NOT NULL
DROP TABLE TaiKhoan
CREATE TABLE TaiKhoan(
IdTaiKhoan INT IDENTITY (1,1) PRIMARY KEY,
IdUser INT,
UserName NVARCHAR(225),
MatKhau NVARCHAR(225),
FOREIGN KEY (IdUser) REFERENCES dbo.Users(IdUser)
)
IF OBJECT_ID('NgonNgu') IS NOT NULL 
DROP TABLE NgonNgu
CREATE TABLE NgonNgu(
IdNgonNgu INT IDENTITY(1,1) PRIMARY KEY,
TenNgonNGu NVARCHAR(225),
TrangThai BIT
)


IF OBJECT_ID('TacGia') IS NOT NULL 
DROP TABLE TacGia
CREATE TABLE TacGia(
IdTacGia INT IDENTITY(1,1) PRIMARY KEY,
TenTacGia NVARCHAR(225),
TrangThai BIT
)

IF OBJECT_ID('NXB') IS NOT NULL 
DROP TABLE NXB
CREATE TABLE NXB(
IdNXB INT IDENTITY(1,1) PRIMARY KEY,
TenNXB NVARCHAR(225),
TrangThai BIT
)
IF OBJECT_ID('TheLoai') IS NOT NULL 
DROP TABLE TheLoai
CREATE TABLE TheLoai(
IdTheLoai INT IDENTITY(1,1) PRIMARY KEY,
TenTheLoai NVARCHAR(225),
TrangThai BIT
)
IF OBJECT_ID('NhaCungCap') IS NOT NULL 
DROP TABLE NhaCungCap
CREATE TABLE NhaCungCap(
IdNhaCungCap INT IDENTITY(1,1) PRIMARY KEY,
TenNhaCungCap NVARCHAR(255),
DIACHI NVARCHAR(255),
SODIENTHOAI VARCHAR(10),
TrangThai BIT
)
IF OBJECT_ID('KhachHang') IS NOT NULL
DROP TABLE KhachHang
CREATE TABLE KhachHang(
IdKhachHang INT IDENTITY(1,1) PRIMARY KEY,
Hoten NVARCHAR(225),
NgaySinh DATE,
GioiTinh BIT,
Sdt VARCHAR(10),
DiaChi NVARCHAR(225),
TrangThai BIT
)

IF OBJECT_ID('Voucher') IS NOT NULL
DROP TABLE Voucher
CREATE TABLE Voucher(
IdVoucher INT IDENTITY (1,1) PRIMARY KEY,
MaGiamGia NVARCHAR(225),
GiamGia DOUBLE PRECISION,
StartsAt DATE,
EndsAt DATE,
SoLuong INT,
TrangThai BIT
)

IF OBJECT_ID('HoaDonBan') IS NOT NULL 
DROP TABLE HoaDonBan
CREATE TABLE HoaDonBan(
IdHoaDonBan INT IDENTITY(1,1) PRIMARY KEY,
IdKhachHang INT,
IdUser INT,
IdVoucher INT,
ngayTao DATE,
NGAYTHANHTOAN DATE,
TENKHACHHANG NVARCHAR(225),
statusPay BIT,
statusInvoice BIT,
TongTien MONEY,
TienKhachDua MONEY,
TienTraLai MONEY,
TrangThai BIT ,
FOREIGN KEY (IdKhachHang) REFERENCES dbo.KhachHang(IdKhachHang),
FOREIGN KEY (IdUser) REFERENCES dbo.Users(IdUser),
FOREIGN KEY (IdVoucher) REFERENCES dbo.VOUCHER(IdVoucher)
)
    


IF OBJECT_ID('Sach') IS NOT NULL 
DROP TABLE Sach
CREATE TABLE Sach(
IdSach INT IDENTITY(1,1) PRIMARY KEY,
IdNhaCungCap INT,
Idtheloai INT,
MaSach NVARCHAR(255),
TenSach NVARCHAR(255),
TrangThai BIT,
FOREIGN KEY (Idtheloai) REFERENCES dbo.TheLoai,
FOREIGN KEY (IdNhaCungCap) REFERENCES dbo.NhaCungCap,
)



IF OBJECT_ID('ChiTietSach') IS NOT NULL 
DROP TABLE ChiTietSach
CREATE TABLE ChiTietSach(
IdCTSach INT IDENTITY(1,1) PRIMARY KEY,
IdSach INT,
MoTa NVARCHAR(225) DEFAULT NULL,
SoLuongTon INT,
GiaNhap FLOAT,
GiaBan FLOAT,
CreatedAt DATE,
UpdateAt DATE,
FOREIGN KEY (IdSach) REFERENCES dbo.Sach(IdSach),
)

IF OBJECT_ID('CTHoaDonBan') IS NOT NULL 
DROP TABLE CTHoaDonBan
CREATE TABLE CTHoaDonBan(
IdHoaDonBan INT ,
IdCTSach INT,
SoLuong INT,
DonGia FLOAT DEFAULT 0,
PRIMARY KEY (IdHoaDonBan,IdCTSach),
FOREIGN KEY (IdHoaDonBan) REFERENCES dbo.HoaDonBan(IdHoaDonBan),
FOREIGN KEY (IdCTSach) REFERENCES dbo.ChiTietSach(IdCTSach)
)


IF OBJECT_ID('NNgu_CTSach') IS NOT NULL 
DROP TABLE NNgu_CTSach
CREATE TABLE NNgu_CTSach(
IdNgonNgu INT,
IdCTSach INT ,
PRIMARY KEY(IdNgonNgu,IdCTSach),
FOREIGN KEY (IdNgonNgu) REFERENCES dbo.NgonNgu(IdNgonNgu),
FOREIGN KEY (IdCTSach) REFERENCES dbo.ChiTietSach(IdCTSach)
)

IF OBJECT_ID('NXB_CTSach') IS NOT NULL 
DROP TABLE NXB_CTSach
CREATE TABLE NXB_CTSach(
IdNXB INT,
IdCTSach INT ,
PRIMARY KEY(IdNXB,IdCTSach),
FOREIGN KEY (IdNXB) REFERENCES dbo.NXB(IdNXB),
FOREIGN KEY (IdCTSach) REFERENCES dbo.ChiTietSach(IdCTSach)
)


IF OBJECT_ID('TGia_CTSach') IS NOT NULL 
DROP TABLE TGia_CTSach
CREATE TABLE TGia_CTSach(
IdTacGia INT,
IdCTSach INT ,
PRIMARY KEY(IdTacGia,IdCTSach),
FOREIGN KEY (IdTacGia) REFERENCES dbo.TacGia(IdTacGia),
FOREIGN KEY (IdCTSach) REFERENCES dbo.ChiTietSach(IdCTSach)
)


IF OBJECT_ID('HOADONNHAPSANPHAM') IS NOT NULL 
DROP TABLE HOADONNHAPSANPHAM
CREATE TABLE HOADONNHAPSANPHAM(
IDHOADONNHAPSANPHAM INT IDENTITY(1,1) PRIMARY KEY,
IDNHACUNGCAP INT ,
IDUsers INT,
NGAYTAODON DATETIME,
TINHTRANGTRATIEN INT,
MOTA NVARCHAR(225),
FOREIGN KEY (IDUsers) REFERENCES dbo.Users,
FOREIGN KEY (IDNHACUNGCAP) REFERENCES dbo.NhaCungCap
)
IF OBJECT_ID('CHITIETHOADONNHAPSANPHAM') IS NOT NULL 
DROP TABLE CHITIETHOADONNHAPSANPHAM
CREATE TABLE CHITIETHOADONNHAPSANPHAM(
IDHOADONNHAPSANPHAM INT ,
IDCHITIETSACH INT ,
SoLuong INT,
priceImport MONEY,
PRIMARY KEY (IDHOADONNHAPSANPHAM,IDCHITIETSACH),
FOREIGN KEY (IDHOADONNHAPSANPHAM) REFERENCES dbo.HOADONNHAPSANPHAM,
FOREIGN KEY (IDCHITIETSACH) REFERENCES dbo.ChiTietSach
)
IF OBJECT_ID('HOADONTRAHANG') IS NOT NULL 
DROP TABLE HOADONTRAHANG
CREATE TABLE HOADONTRAHANG(
IDHOADONTRAHANG INT IDENTITY(1,1)PRIMARY KEY,
IDKHACHHANG INT ,
IDUSERS INT,
IDHOADONBANHANG INT,
NGAYDOIHANG DATETIME,
mota NVARCHAR(225),
FOREIGN KEY (IDKHACHHANG) REFERENCES dbo.KhachHang,
FOREIGN KEY (IDUSERS) REFERENCES dbo.Users,
FOREIGN KEY (IDHOADONBANHANG) REFERENCES dbo.HoaDonBan
)
IF OBJECT_ID('chitiethoadonTRAHANG') IS NOT NULL 
DROP TABLE chitiethoadonTRAHANG
CREATE TABLE chitiethoadonTRAHANG(
IDchitiethoadonTRAHANG INT IDENTITY(1,1) PRIMARY KEY,
IDHOADONTRAHANG INT ,
IDCHITIETSACH INT ,
SOLUONG INT,
IDHOADONBANHANG INT,
NGAYDOIHANG DATETIME,
mota NVARCHAR(225),
GIA FLOAT,
FOREIGN KEY (IDHOADONTRAHANG) REFERENCES dbo.HOADONTRAHANG,
FOREIGN KEY (IDCHITIETSACH) REFERENCES dbo.ChiTietSach,
)
IF OBJECT_ID('hoadonthaydoisanpham') IS NOT NULL 
DROP TABLE hoadonthaydoisanpham
CREATE TABLE hoadonthaydoisanpham(
IDhoadonthaydoisanpham INT IDENTITY(1,1) PRIMARY KEY,
Idusers INT ,
IDKHACHHANG INT ,
IDHOADONBANHANG INT,
idsach int,
idchitietbanhang int,
ngaytaohoadon date,
mota NVARCHAR(225)
FOREIGN KEY (Idusers) REFERENCES dbo.Users,
FOREIGN KEY (IDKHACHHANG) REFERENCES dbo.KhachHang,
FOREIGN KEY (IDHOADONBANHANG) REFERENCES dbo.HoaDonBan,
FOREIGN KEY (idsach) REFERENCES dbo.Sach,
FOREIGN KEY (idchitietbanhang) REFERENCES dbo.ChiTietSach
)
IF OBJECT_ID('chitietthaydoihoadon') IS NOT NULL 
DROP TABLE chitietthaydoihoadon
CREATE TABLE chitietthaydoihoadon(
IDchitietthaydoihoadon INT IDENTITY(1,1) PRIMARY KEY,
IDhoadonthaydoisanpham INT ,
IDCHITIETSACH INT ,
soluong int
FOREIGN KEY (IDhoadonthaydoisanpham) REFERENCES dbo.hoadonthaydoisanpham,
FOREIGN KEY (IDCHITIETSACH) REFERENCES dbo.ChiTietSach,
)
IF OBJECT_ID('chitietthaydoisanpham') IS NOT NULL 
DROP TABLE chitietthaydoisanpham
CREATE TABLE chitietthaydoisanpham(
IDchitietthaydoisanpham INT IDENTITY(1,1) PRIMARY KEY,
IDchitietthaydoihoadon INT ,
IDCHITIETSACH INT ,
soluong int
FOREIGN KEY (IDchitietthaydoihoadon) REFERENCES dbo.chitietthaydoihoadon,
FOREIGN KEY (IDCHITIETSACH) REFERENCES dbo.ChiTietSach,
)





